[Link to Page](https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [2]:
from __future__ import print_function
import torch

In [3]:
torch.__version__

'1.7.1+cpu'

# Tensors

In [5]:
# 초기화되지 않은 행렬

x = torch.empty(5,3)
print(x)

tensor([[-2.5353e+30,  1.0141e+31,  2.5223e-44],
        [ 2.5353e-38,  2.5715e-38,  9.9179e-38],
        [ 1.0433e-37, -3.4391e-12,  1.6615e+35],
        [ 6.7010e+22,  1.2404e-14,  3.0478e+32],
        [ 1.8467e+20,  2.6798e+20,  3.8678e-14]])


In [8]:
# 무작위로 초기화된 행렬

x = torch.rand(5,3)
print(x)

tensor([[0.5536, 0.7699, 0.1722],
        [0.7529, 0.0195, 0.4441],
        [0.8291, 0.1925, 0.0038],
        [0.7561, 0.4158, 0.7893],
        [0.1046, 0.8206, 0.2356]])


In [11]:
# 0으로 초기화된 행렬, type = long
# default = float

x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [13]:
# 직접 tensor 생성

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [17]:
# 기존 tensor를 바탕으로 새로운 tensor

x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [19]:
# x와 같은 크기의 난수 행렬

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[ 1.0783,  0.0822, -0.3893],
        [-1.0252, -0.0533, -0.9640],
        [-0.0503, -0.9245, -0.6729],
        [-0.8756,  0.4166,  2.1495],
        [-0.4141,  1.6754,  1.7914]])


In [21]:
# 행렬의 크기

print(x.size())

torch.Size([5, 3])


# Operations

In [22]:
# add 1

y = torch.rand(5,3)
print(x + y)

tensor([[ 1.3612,  0.6154,  0.5100],
        [-1.0240,  0.0561, -0.0833],
        [ 0.2819, -0.5354, -0.6115],
        [-0.1938,  1.0990,  2.8548],
        [ 0.0442,  2.2723,  2.7342]])


In [23]:
# add 2

print(torch.add(x,y))

tensor([[ 1.3612,  0.6154,  0.5100],
        [-1.0240,  0.0561, -0.0833],
        [ 0.2819, -0.5354, -0.6115],
        [-0.1938,  1.0990,  2.8548],
        [ 0.0442,  2.2723,  2.7342]])


In [24]:
# 결과 tensor를 인자로 제공할 수 있다

result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 1.3612,  0.6154,  0.5100],
        [-1.0240,  0.0561, -0.0833],
        [ 0.2819, -0.5354, -0.6115],
        [-0.1938,  1.0990,  2.8548],
        [ 0.0442,  2.2723,  2.7342]])


In [25]:
# inplace 연산 (method_)

y.add_(x)
print(y)

tensor([[ 1.3612,  0.6154,  0.5100],
        [-1.0240,  0.0561, -0.0833],
        [ 0.2819, -0.5354, -0.6115],
        [-0.1938,  1.0990,  2.8548],
        [ 0.0442,  2.2723,  2.7342]])


In [29]:
# indexing like numpy

print(x[:,:-1])

tensor([[ 1.0783,  0.0822],
        [-1.0252, -0.0533],
        [-0.0503, -0.9245],
        [-0.8756,  0.4166],
        [-0.4141,  1.6754]])


In [30]:
# reshape = view

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # (2, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
# tensor의 값이 하나라면 .item()을 이용해여 숫자 값만 얻을 수 있다

x = torch.rand(1)
print(x)
print(x.item())

tensor([0.2614])
0.26141488552093506


# Numpy 변환

In [39]:
import numpy as np
# Tensor2Numpy

a = torch.ones(5)
print(a, a.dtype)

b = a.numpy()
print(b, b.dtype)

tensor([1., 1., 1., 1., 1.]) torch.float32
[1. 1. 1. 1. 1.] float32


In [40]:
# 값이 함께 바뀜

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [41]:
# Numpy2Tensor

a = np.ones(5)
b = torch.from_numpy(a)

print(a, a.dtype)
print(b, b.dtype)

[1. 1. 1. 1. 1.] float64
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) torch.float64


In [43]:
# 역시 값이 함께 바뀜

np.add(a, 1, out = a)
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# CUDA

In [44]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!