[Link to Page](https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html)

In [1]:
import torch

- **autograd** : Tensor의 모든 연산에 대해 자동 미분
- `.requires_grad` 속성을 참으로 설정 시, 해당 Tensor의 모든 연산을 추적
- 계산이 완료된 후, `.backward()`를 호출하여 gradient를 자동으로 계산할 수 있다.
- 추적을 중단하려면, `.detach()`를 호출
- 혹은 `with torch.no_grad()`: 로 감쌀 수 있다.

# Requires_grad / grad_fn

In [2]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
# y 는 연산 결과로 생성되었으므로, grad_fn을 갖는다.

y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
# grad_fn은 어떤 연산이 이루어졌는지 기록하는 듯..( backprop때 사용하려고 ? )
z = y * y * 3
out = z.mean()

print(z,"\n",out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) 
 tensor(27., grad_fn=<MeanBackward0>)


In [6]:
# default : requires_grad  = False!
a = torch.ones(2, 2) + 1
a = (( a * 3 / (a - 1)))

print(a)
print(a.requires_grad)

tensor([[6., 6.],
        [6., 6.]])
False


In [7]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [8]:
b = (a * a).sum()
print(b)
print(b.grad_fn)

tensor(144., grad_fn=<SumBackward0>)


# Gradient

In [9]:
# out : 하나의 스칼라
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [10]:
# out.backward() == out.backward(torch.tensor(1.))
out.backward()

In [11]:
# y = x + 2
# z = y * y * 3
# out = z.mean()

# x.grad() == d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

v = torch.tensor([0.1,1,0.0001], dtype= torch.float)
y.backward(v)
print(x.grad)

tensor([-1396.1807,   713.8336,  -784.7281], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [15]:
print(x.requires_grad)
print((x**2).requires_grad)

# stop tracing
with torch.no_grad():
    print( (x**2).requires_grad)

True
True
False


In [16]:
# detach --> 추적 막기
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False


In [17]:
# requires_grad 값은 다르지만 같다
print(x.eq(y).all())

tensor(True)
